export const storeProducts = [
  {
    id: 1,
    title: "Embroidered Classic Hoodie",
    img1: "img/classic-hoodie.png",
    img2: "img/fuego-close.jpg",
    price: 40,
    company: "Fuego",
    info:
      "Classic Embroidered Logo Hoodie, perfect for chilling in any season of the year. Embroidery and branding all produced by Fuego. Wrap yourself in the warm embrace of this thick, 8oz. Gildan Heavy Blend 50/50 Hoodie. Even through several washes, the airjet yarn is specially blended to remain soft and resist pilling, which are those unwanted little tufts of fabric that spring up on your clean clothes after washing.",
    inCart: false,
    count: 0,
    total: 0,
    size: "?",
    out: true,
    hidden: false,
  },
  {
    id: 2,
    title: "Embroidered Classic Tee",
    img1: "img/fuego-natural.png",
    img2: "img/fuego-close.jpg",
    price: 20,
    company: "Fuego",
    info:
      "Classic Embroidered Logo Tee, Natural colored. Embroidery and branding all produced by Fuego. This is the classical natural flavor of Fuego and intends to repeat designs using this off white/natural color scheme with vibrant designs and ideas.",
    inCart: false,
    count: 0,
    total: 0,
    size: "?",
    out: false,
    hidden: false,
  },
  {
    id: 3,
    title: "Embroidered Rust Logo Tee",
    img1: "img/rust-natural.png",
    img2: "img/rust-close.jpg",
    price: 20,
    company: "Fuego / Rust",
    info: "Only for the wisest of wisemen...",
    inCart: false,
    count: 0,
    total: 0,
    size: "?",
    out: false,
    hidden: false,
  },
];

export const detailProduct = [
  {
    id: 1,
    title: "Embroidered Classic Hoodie",
    img1: "img/classic-hoodie.png",
    img2: "img/fuego-close.jpg",
    price: 40,
    company: "Fuego",
    info:
      "Classic Embroidered Logo Hoodie, perfect for chilling in any season of the year. Embroidery and branding all produced by designer.",
    inCart: false,
    count: 0,
    total: 0,
    size: "?",
    out: true,
  },
  {
    id: 2,
    title: "Embroidered Classic Tee",
    img1: "img/fuego-natural.png",
    img2: "img/fuego-close.jpg",
    price: 20,
    company: "Fuego",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    size: "?",
    out: false,
  },
  {
    id: 3,
    title: "Embroidered Rust Logo Tee",
    img1: "img/rust-natural.png",
    img2: "img/rust-close.jpg",
    price: 20,
    company: "Fuego / Rust",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    size: "?",
    out: false,
  },
];
